### ISSUE TITLE
Docs for Modernizr/Legacy Browser 'Deep support' are out of date

### ISSUE THREAD

**Issue by mhokane** [WickyNilliams/enquire.js#143] opened 2015-12-31 17:04 UTC
Modernizr 3 ditched yepnope.js so the technique listed won't work anymore 🙁

I'm doing this for now: https://medium.com/@MarkHoKane/modernizr-ditched-yepnope-js-how-to-load-your-polyfill-fec5dddb5867#.dg17qmpuy

**Updated with another method:** https://medium.com/@MarkHoKane/implementing-older-browser-support-for-enquire-js-30874a1fd18b#.g2n1uzsz6

**Comment by monolux** [comment] 2016-02-28 22:18
Good to know!

**Comment by WickyNilliams** [comment] 2017-03-07 11:45
I think I'll change the docs to recommend bundling the polyfill rather than asynchronously loading it. Closing this as a duplicate of #116

**Closed by WickyNilliams** 2017-03-07 11:45 UTC
